### ISSUE TITLE
make link tittle on example 1

### ISSUE THREAD

**Issue by adiansyahgit** [toepoke/mapsed#9]
hi, im getting a problem. trying to add link or creating a link on the tittle, in custom map example 1. i add <a href="" tag but it didnt work. please help

**Comment by toepoke** [comment]
Hi,

Please reproduce the issue on http://plnkr.co/ and add the link here and I'll take a look.

Thanks.

**Comment by adiansyahgit** [comment]
oh sorry for my late replay. somehow i solved the problem.
the maps is very useful. thanx

**Comment by toepoke** [comment]
Cool, glad you're sorted.
